name: CI

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]

jobs:
  build:
    runs-on: windows-latest
    steps:
      - uses: actions/checkout@v2
      - uses: actions/setup-java@v1
        with:
          java-version: '8'
          java-package: jre
          architecture: x64
          
      - name: Compile DEH File
        shell: cmd
        run: call build.bat
        
      - name: Upload final DEH file zipped
        uses: actions/upload-artifact@v2
        with:
          name: dehacked
          path: |
            dehacked.deh